name: vaktijaba_fl
description: Vaktija za BiH

uses: subosito/flutter-action@v2.10.0

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1000

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_qiblah: ^2.0.2
  scrollable_positioned_list: ^0.3.2
  geolocator: ^7.6.0
  hijri: ^3.0.0
  flutter_local_notifications: ^9.7.0
  provider: ^6.0.3
  flutter_slidable: ^2.0.0
  mailto: ^2.0.0
  share_plus: ^4.0.10
  url_launcher: ^6.1.5
  shared_preferences: ^2.0.15
  quiver: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/vaktija/
    - assets/icons/
